<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# Literautre Review {#Review}

Individual characteristics such as education and income are associated with fertility intentions and outcomes. The processes leading to differences in fertility outcomes by individual characteristics influence the size of the gap between fertility intentions and outcomes. Social network processes are underlying determinants of the fertility gap, influencing different individuals to varying degrees in addition to underlying individual characteristics. The analysis of such network processes is undertaken both on the small- and large-scale. Small-scale analyses require thorough qualitative sources and complex modelling. Growing analysis of regional fertility is taking place in Europe, particularly with a focus on education [@wood2020] and income [@campisi2020;@nisen2020]. Despite the growth in the two scales, the sub-regional, local scale remains relatively unexplored. The current literature is addressed by three sections. First, the processes of social networks at the interpersonal level; second by diffusion at the large scale; and finally the connection of the two scales to form an overarching theory. 

## Small-Scale Diffusion
The transmission of fertility norms, ideals and intentions occurs on a hierarchical scale; the first level is the individual, and the final is the nation. Leaving the aggregate scale and focussing on the individual, the family, friends, and workplace acquaintances form a personal network unique to each individual. In a landmark paper, @watkins1995 addresses social interaction and networks as influencing reproductive behaviour. Watkins argues that not only the spread of new technologies and the diffusion of ideas are important in fertility decline, but also the personal networks of individuals. In further clarity,@bongaarts1996 argue that diffusion is an independent actor that leads to changes in fertility behaviour, as social interaction produces new ideas relating to childbearing as a variable of its own. The authors emphasise how information is exchanged and thereafter enforced or encouraged. That is, changes in fertility occur due to structural change, and diverge from the Second Demographic Transition (SDT), which largely focusses on the individual, while lacking acknowledgement of social networks [@bernhardt2004]. @bernardi2014 also note the delayed adoption of social network theory in the Global North due to the assumption that in individualistic societies, social considerations are not effective in influencing childbearing intentions. That is, small- and large-scale analyses of diffusion remain somewhat separate and scale-dependent despite relying on the same underlying processes. 

Building upon the above theoretical developments and with high-quality data, @balbo2014 find fertility behaviour to be influenced by friendship circles. If an individual has a friend who has children, the risk of having a child himself/herself increases, yet 2 years following the birth of a friend’s child, network effects begin to diminish. The friendship influences on fertility appear to increase with age to 28 years old, with declining influence of social networks thereafter, thereby noting the temporal and variant nature of social network effects. The contagion between friends and members of a network is also developed by @lois2014 who emphasise the process of ‘social contagion’ combining three different social network effects: social learning, social pressure, and social opportunity cost. In comparison, @bernardi2014 identify social learning, social pressure, social contagion and social support as drivers of fertility change, with overarching points of interdependence. The exact processes and wording differ, but the overarching process remain unchanged. Social contagion is present within networks of people, and leads to differences in intended and actual fertility. 

As social interactions occur at the interpersonal scale, the measurement and significance of such relationships is most appropriate at the micro level. In a comparative study of West and East Germany, @bernardi2007 identify two elements of fertility decision-making, firstly ‘individual and structural characteristics of networks’ and ‘social mechanisms’ between individuals at the core. In the same study of 54 people, network size varies between 14 and 17. The actual agents enabling exchange of ideas relating to childbearing are the social mechanisms within the social network. @bernardi2007 also note the complexities such as heterogeneity in network structures, and differences between geography and gender. Measuring these is difficult, with few surveys being able to answer hypotheses of social interaction due to lack of depth and network [@rossier2009].

The endogenous networks that carry information and further the transition to parenthood have been tested with agent-based simulation models. For example, social interactions affecting first-birth probabilities for Austrian women [@diaz2011]. In a comparative agent-based modelling approach, Nomes and colleagues (2019) use Belgian census data to show that the two-child family norm and the homogenisation of this ideal throughout the country led to rising as well as falling fertility in different parts of Belgium. @fent2013 also use agent-based modelling by incorporating agents’ heterogeneity and network structure, and find a positive association between network size and fertility outcomes.

Only small-scale, qualitative studies can capture the origins of social contagion, while the grander process of diffusion across space can grasp at the outcomes of such processes. The literature has shown that individual characteristics are not sufficient in identifying the processes that lead to fertility intentions and outcomes, but rather, the social processes between individuals, groups and neighbourhoods are significant and should not be overlooked. Without being able to model individuals, the inclusion of a spatial term at the aggregate level closely mimics the missing link of neighbour-to-neighbour contagion. In sum, the influence of social networks can and should be tested at the aggregate scale, but the complexity and requirement of assumptions is not understated.

## Large-Scale Diffusion
Despite the theoretical reliance on interpersonal contagion, the sources of data within this research require aggregation. Since the pivotal works regarding the fall in fertility in the Global North during the latter half of the 20th century [@vandekaa1987;@lesthaeghe1995], aggregate-level diffusion has been tested within Demography. Despite criticisms of the SDT relating to simplification and a false permanence [@szreter1993], the underlying processes that underpin the theory remain relevant and mainstream [@casterline2001]. The ability of women to pursue careers above raising children is central to the SDT, based in individualism and women’s agency in relation to childbearing [@becker1981;@vandekaa1987]. The ideals of the SDT have already spread throughout England, and the individualism that is now common challenges social network effects routed in community. Therefore, there is a slight disconnect between the previous and current sections, and the hangovers of the SDT fertility-decline based theory are not as relevant as previous, yet, the diffusion processes are. 

@casterline2001 cites three bodies of work forwarding the grand theory of diffusion: the first being behavioural innovation (such as fertility control), the second is derived from the “innovation diffusion” concept led by ideational theories. The third is based in social dynamics, relating to the channels by which the two former dynamics forward the spread of behaviours and ideas. While focussing on social dynamics, @casterline2001 terms social effects as effects derived largely from social learning and social influence. Social, interpersonal effects are therefore at the core. This model of social effects bares the simple premise “changes in the knowledge and behaviours of some individuals affect the likelihood that other individuals will change their knowledge and/or behaviours” [@casterline2001 p.17]. @manski1993 clarifies with three effects; with endogenous relating to social interactions; contextual being the group in which one resides; and correlated being similarities between individuals in similar environments [@durlauf2001]. 

@klusener2013 are one of the first examples to use sub-national scale in spatially modelling TFR, where the diffusion of non-marital fertility behaviours are influenced by external and internal borders from 1960 to 2007. The diffusion of socioeconomic norms and values, based on the Easterlin supply and demand hypothesis is shown in Italy from 1952 to 1995 through a Spatial Lag model [@waldorf2002]. This approach, by @waldorf2002 spatially models 18 regions, ending with an adjusted R2 value of 0.9, which raises more concern than confidence as diffusion of fertility behaviour is unlikely to explain the vast majority of child-bearing decisions. In a comparable paper to this dissertation, @campisi2020 compare three spatial autocorrelation regression models, two multilevel models, and OLS, concluding that the Spatial Lag model is the most appropriate to the data and phenomena at play. The variables included in the model are TFR, population density (log scale), share of apartment housing, Gross Domestic Product (GDP) per capita, employment rate, share of employment in agriculture and prevalence of divorce. Spatial autocorrelation of residuals decreases from the OLS model to the Spatial Lag Model, the Spatial Error Model and the Spatial Durbin Model. Despite being highly relevant, the approach lacks diverse non-economic variables that may account for spatial autocorrelation such as ethnicity. In addition, the authors do not show diagnostics tests such as the Robust Larange Multiplier test, which may disprove the existence of endogenous interaction effects. Analysing the residuals of autoregressive models is not useful, as a vast fall in residual spatial autocorrelation is certain when including spatial autoregression in the model formula. @vitali2017 also approach the data similarly, by testing fertility diffusion through the time frame 1991 to 2010 in 110 regions of EU. In addition to using two spatial models, Vitali and Billari find the spatial element of fertility to remain when controlling for significant socio-demographic variables, but with only four variables included.

At the opposite scale, very-low level analysis of fertility is rare. Within fertility research, a model including a spatial term below the regional level has not, to my knowledge, been done. For instance, @basten2011 model the convergence of fertility trends in Austria, Germany and Switzerland alongside a very-low level analysis of Bremen, Germany. Yet, no spatial element is included within the model. While this dissertation focusses on England and Wales, a similar working paper by @boyle2007 fills a geographical gap by modelling fertility clusters in Scotland, split into 10,000 neighbourhoods. A smaller scale is used when compared to this dissertation; Consistent Areas Throughout Time (CATTs), which enables a comparison of census data from between 1981, 1991 and 2001. Despite a fine geography, the models lack a spatial element, and the use of CATTs result in areas with very few people and births. As is common in small-scale analyses, crude geographic aggregations are often used within these papers [@boyle2007]. The lack of data with well-justified boundaries, as in the case of CATTs, separated by population alone, leads to the identification of spatial autocorrelation that may be due to one area being split in two. 

Within the UK, few papers have modelled fertility with a spatial principle. In multiple works based in the UK, the size of the settlement, population density and selective migration, which is based on fertility intentions, are significant to fertility [@kulu2007; @kulu2009; @kulu2013; @kulu2014]. The methodologies of Kulu and UK-based spatial analysis largely remain within hazard models and avoiding the retention of neighbourhood boundaries through aggregation. @fiori2014 use a hazard model to predict outcomes for five agglomerated geographies by rural and urban context, concluding that geography is relevant to first births, but not higher order births. The base geography is Lower Super Output Area (LSOA), and the issue of using such a small geography is overcome by the merging the data. @jaadla2018, in a larger-scale geography to Fiori and colleagues, identify the fertility transition in England and Wales between 1851 and 1911 beginning in areas of high population and high technological density, such as cotton mill towns in the North West. In the early 20th century and 2001/2011 context of London, Jaadla et al. (2020) are working on a spatial model including general fertility rate as the dependent variable, and population density, share of married women, share of managers, share of elementary occupations and share of foreign born as explanatory variables. Jaadla and colleagues use the 624 wards of London in the latter data frame. Similar to @jaadla2018, historic modelling has identified the fertility transition processes in Sweden and Prussia, but with greater attention to spatial processes both in theory and in model formulae. @klusener2019 model fertility in Sweden from 1880 to 1900, finding the diffusion of fertility decline was less spatially clustered in elite communities than in the poor communities, that is, the elite led the fertility decline and through quicker corridors of communication. In a similar vein, @goldstein2014 identify corridors of fertility diffusion in Prussia, utilising spatial autocorrelation determinants in identifying spatial clustering, and testing the presence of autocorrelation through the omission of variables. Both papers argue for greater attention to geographic location, and spatial approaches have grown in prominence but largely remained at the regional level.

## Conclusion: Literature Review
Some research has shown that the inclusion of and complication caused by spatial dependence is often unnecessary, and modelling aggregate fertility without a spatial element yields useful results [@hank2001; @sobotka2002; @bujard2017;@fox2019]. Such approaches can also avoid violating the OLS assumption of non-dependence, as influence between regions can often be considered similarly to the influence between countries at such large scales. The scale of such studies is also an understated disadvantage, in capturing what are in essence social network effects at the relatively large geographic NUTS-3 sub-national division. Within this sub-national setting, populations range from 150,000 to 800,000. Country diagnostics are potentially too grand to display individual behaviour [@bryan2016], and this literature review has also found regional diagnostics to be too grand to display individual behaviour. Both the regional and national approaches incur a far departure from the micro and meso scale where fertility-related decision-making takes place. That is, social contagion occurs in the individual and interpersonal space where ideas are formed, norms expected and behaviours encouraged or discouraged, and remaining closely tied to this meso level allows the outcomes of spatial processes to be measured. 

The overarching processes of fertility change are spatial and interpersonal; processes captured at the neighbourhood scale more so than the regional or national. There are two relevant gaps in the literature addressing the processes of spatial diffusion. First, UK-specific research is limited. Although Local Authorities have been used in analysing TFR, these papers are largely descriptive, with the use of spatial autocorrelation rarely used  (with the exception of Walford and Kurek, 2016). Second, an exploration of model types at the sub-regional, local scale is very rare. Spatial sub-national analyses often include economic factors within the models [e.g. @nisen2020], but lack important variables such as ethnicity. The intention of the following sections is therefore to build an analytical analysis of local fertility taking into account previous research.


### Aims and objectives {#Aims}
The overarching aim of this dissertation is to identify whether fertility diffusion is present at the MSOA level within England and Wales. That is, the exchange of fertility behaviour between neighbourhoods. Three questions, which also form the oncoming results section of this dissertation are therefore as follows, followed by the research aims addressing the research questions:  
&nbsp; 

**Descriptive**: Is there spatial autocorrelation in fertility outcomes, and if so, has this weakened or strengthened over time (from 2002-2018)? </p> 
&nbsp;  

**Theoretical**: If existent, does spatial autocorrelation remain when accounting for compositional and contextual determinants?</p>
&nbsp;  

**Methodological**:
Does the inclusion of a spatial autoregressive element to base OLS formula aid in the explanatory power of small-scale fertility outcomes, signifying the necessary inclusion of neighbour-to-neighbour fertility diffusion?</p>
&nbsp;  

1.	Test for spatial autocorrelation in Age-Specific Fertility Rates (ASFRs) and TFR from 2002 to 2018.
      i) Calculate Global Moran’s I and illustrate Local Moran’s I.
&nbsp;  

</p>2.	Build an OLS model and examine the spatial autocorrelation of model residuals in the addition of each variable. 
      i) Add the seven variables stepwise. 
      ii) Use spatial tests to identify which model is best-fitted. </p>
&nbsp;  

3.	Build four spatial autocorrelation models to test the neighbour-to-neighbour diffusion hypothesis.
      i) Spatial Lag Model (SAR), Spatial Error Model (SEM), Spatial Durbin Model (SDM) and Spatial Durbin Error Model (SDEM).
      ii) Describe the most appropriate final model results and implications.

