# Discussion {#Discussion}

## Limitations
The limitations of this dissertation largely refer to the data used and issues in modelling the drivers of spatial dependence. Compared to papers modelling fertility differentials within one socio-demographic classification (e.g. cohabiting childbearing in Vitali et al., 2015), the analysis of TFR as a whole is difficult to draw conclusions from. TFR is a comparatively less accurate measure of fertility as compared to cohort fertility and tempo-adjusted rates [@kohler2002a]. In addition, the birth and population data come from different sources, with the issue of migrant counts leading to potential over-estimations of TFR in areas of high short-term migration. The presence of students within an MSOA also distorts ASFRs and TFR due to MSOAs being small in size and students being geographically concentrated. There are also large fluctuations year-by-year in MSOA populations, and a possible small change in population would change ASFRs and TFR to a large degree. 

Diffusion is temporal as well as spatial, and the use of panel data would allow time to be included, whereas the cross-sectional spatial econometric models included do not take time into account, assuming simultaneous changes throughout the model. The addition of time would allow for a more complex model to be built exploring the changes in spatial autocorrelation from 2002 to 2018, however, the number of available variables would decrease. Three spatial issues are clearly present. First, the identification of autocorrelation nay be mis-specified due to the arbitrary designation of polygons derived from census tracts [@anselin1988], referring to the Modifiable Areal Unit Problem caused by areal agglomeration [@fotheringham1991]. Under slightly different boundaries that more closely fit the notion of neighbourhood, the interpretation of the social processes would differ. That is, the spatial, diffusion-led methodology and results rely upon the 2011 MSOA boundaries being legitimate neighbourhoods. Second, the ecological fallacy is present, meaning aggregation leads to applying one variable value to multiple individuals. Third and similar to the Modifiable Areal Unit Problem, Galton’s Problem refers to areas being similar to one another simply due to the boundaries drawn, rather than being independent observations and leading to a misspecification of interaction [@bivand2013]. 

## Neighbour-to-neighbour fertility diffusion
The diffusion of fertility behaviours from neighbour-to-neighbour is significant within the models due to the impact of spatially lagged TFR improving model performance from the OLS to the SAR model, however, the significance is overshadowed in part by other spatial processes. In the aims and objectives section, it was hesitantly assumed that the spatial autocorrelation of TFR would have undergone significant changes between 2002 and 2018. Changes in the spatial dependence of ASFRs occurred, and the spatial autocorrelation of TFR increased, particularly following 2014. The significant spatial dependence of the OLS residuals answered question two in the Moran’s I value of 0.19 and significance below the 0.001 level. The third research question became difficult to answer due to the borderline-significant RLMlag value, bringing into question whether spatial autoregression in TFR is as significant as anticipated and whether network effects are minimised due to boundaries drawn or a weakness of network effects. The primary results of the final, SDM model find education and ethnicity to be the key drivers in local fertility rates within England and Wales, and the compositional variables are more significant than the contextual variables, but the measurable strength of social networks cannot be intuitively derived. That is, population density and social housing are non-significant regarding the total effect of the model, although the total effect hides subtleties between the direct and indirect effects. The inclusion of lagged explanatory variables and associated indirect effects may be viewed as contextual influences in a neighbourhood affecting TFR elsewhere. The following discussion is largely split by the research questions; in descriptive, methodological and theoretical considerations.

The SDM provides a more nuanced view of local-scale drivers of fertility in separating direct form indirect effects. The difference between indirect and direct effects appears to be linked to the degree of compositional or contextual influence. That is, the neighbourhood ($j$) adjoined to an area ($i$) may influence the fertility intentions and behaviours of women and men in area $i$. Therefore, the SDM direct and indirect effects may portray such outcomes, as indirect effects are not compositional and direct effects may be both. For instance, the role of education is negative within $i$ as a largely compositional variable, however, when living next to an area ($j$) of increasing education level, the fertility outcomes of women in $i$ increase. The fertility intentions and outcome differentials between immigrants and natives is well documented within England and Wales [@robards2016], and the variance by ethnic group is shown in the highly significant direct effects within a neighbourhood but generally lacking indirect, contextual effects. 

Fitting well-within recent changes in the relationship between GDP and fertility, income displays an overall positive effect on TFR. This differs from the bivariate analysis of TFR and income as well as the OLS model. When accounting for endogenous and exogenous spatial dependence, income is positively associated with TFR. As opposed to OLS, SAR and SEM results, the role of population density appears to be negative, in line with UK-based research [e.g., @kulu2014]. The role of indirect effects are highly significant, perhaps suggesting that the contextual effect of population density is highly linked to not only one neighbourhood, but also the surrounding areas. Divorce prevalence has a positive effect on fertility, potentially relating to a remarriage effect, however, the influence of a neighbour’s divorce prevalence does not appear to be significant, deviating from network effect theory. Social housing also exerts only direct impact on TFR. The non-religious variable intends to show secularism and a loss of attachment to norms, and throughout the modelling process, non-religiousness is generally the weakest determinant, likely being useful in historic predictors of fertility but not applicable to contemporary contexts.   

Spatial autocorrelation is not only derived from neighbours’ influence, but also also arising from spatial dependence relating to a geographic and social clustering of similar behaviours [@darmofal2015]. The SEM captures this effect more so than any other model, and as seen in RLMlag test, the presence of neighbour-to-neighbour diffusion is less significant than network theory suggests. The RLMlag result alters the discourse, as diffusion cannot be confidently stated to be the driver of spatial dependence. Nonetheless, geography matters even without concretely identifying the exact spatial processes at the individual level. As famously stated by George Box, “all models are wrong, but some are useful”. The models including error are not as useful or parsimonious as the SAR model or SDM which incorporate the spatial autoregression of fertility.   

The context in which a social network is situated will affect the influence of fertility behaviours on others, and may determine the lesser significance when compared to other aggregate approaches in the literature. At the European regional scale, the spatial autoregression of TFR has been proven to be highly significant [@campisi2020]. European wide research, and to an extent the scale of this dissertation, generalise social processes across the entire network. To clarify, Southern European networks are markedly close-knit and strong [@micheli2000] and therefore neighbour-to-neighbour transmission of fertility behaviours is expected to be more significant in Italy than in England and Wales. In the English and Welsh context, the determinants of fertility may be increasingly linked to individual, non-norm based effects, thereby causing social interactions to host less influence in a person’s decision-making processes [@bernardi2014]. The 2011 model captures a snapshot of the two countries, where the diffusion of norms regarding non-marital childbirth and divorce is complete, with decisions now led largely by individual, rather than societal expectations. Therefore, the current diffusion process rests almost entirely on the social networks between individuals, households and neighbourhoods. However, these processes, and associated social contagion, do not appear to be as significant in the English and Welsh contexts as compared to less individual-led societies. 

The central critique of European-wide approaches to fertility analysis is the whole-nation bias of aggregate macro-level comparison that oversimplifies and misdiagnoses demographic processes [@rokkan2009]. The sources of whole-nation bias are also present at the regional scale. The problem persists within this dissertation by analysing the 7,200 MSOAs of England and Wales simultaneously. Further research should aim to disaggregate the spatial processes by stratifications such as town, age group or ethnicity. Using similar methodologies in this dissertation but with parity-specific and age-specific data would be a natural next step. In overcoming whole-nation bias and trying to reduce the methodological distance to the individual processes, the research aims of the study could be analysed at the LSOA level - areas roughly one sixth the size of the current MSOA. The use of unaltered LSOA boundaries is impractical due to very low numbers of births and low populations. However, the combination of LSOAs based on shared characteristics could be an avenue for future research as done by @fiori2014. Instead of agglomeration based on the rural/urban context as done by Fiori and colleagues, LSOAs could be combined to form more cohesive ‘neighbourhoods’, which may overcome some error incurred from ONS aggregation methods 

An alternative methodology to spatial econometrics that can identify the neighbourhood and social networks is agent-based modelling and simulation, which is becoming more common and mainstream in demographic research [@silverman2013;@reinhardt2018]. In future, a combination of methods is recommended, namely with the addition of agent-based modelling in taking the macro-level approach to the meso- and micro-level, where the processes of social contagion take place and the idea of a neighbourhood formulated. The role of space and spatial dependence is highly significant in fertility outcomes, and in moving closer to the individual, this research has bridged a gap between the micro- and macro-scale. The main question that needs to be addressed further relates to why social network influence is not as stark as theories suggest, and whether intricacies exist within groups of the population. Socio-demographic compositional variables are the dominant determinants of fertility outcomes, while contextual variables are comparatively weak. Despite being central, individual characteristics do not explain fertility outcomes alone, taking place alongside increasingly complicated spatial processes.

